# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-24 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressid', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
                ('phonenumber', models.CharField(max_length=30)),
                ('recipient', models.CharField(max_length=30)),
                ('detaaddress', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('buycount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodName', models.CharField(max_length=30)),
                ('goodPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('buyCount', models.IntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinish', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('orderTime', models.DateTimeField()),
                ('orderNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('uPassword', models.CharField(max_length=20)),
                ('uEmail', models.CharField(max_length=30)),
                ('uPhoneNumber', models.CharField(max_length=15)),
                ('uAddr', models.CharField(max_length=50)),
                ('uRegDate', models.DateTimeField()),
                ('isactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='userOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Orders'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo'),
        ),
        migrations.AddField(
            model_name='addrinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo'),
        ),
    ]
