# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import usercenter.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddrInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressid', models.IntegerField(default=0)),
                ('phonenumber', models.CharField(max_length=30)),
                ('recipname', models.CharField(max_length=30)),
                ('detaaddress', models.CharField(max_length=50)),
                ('postcode', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buycount', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Copa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copaname', models.CharField(max_length=30, verbose_name='合作社名称')),
                ('copasec', models.CharField(max_length=80, verbose_name='合作社介绍')),
                ('copaadd', models.CharField(default=None, max_length=80, verbose_name='合作社地址')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodname', models.CharField(max_length=30, verbose_name='商品名')),
                ('gooddesc', models.CharField(max_length=80, verbose_name='商品介绍')),
                ('goodprice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品价格')),
                ('img', models.ImageField(default=None, storage=usercenter.storage.ImageStorage(), upload_to='image', verbose_name='图片')),
                ('salecount', models.IntegerField(default=0, verbose_name='销量')),
                ('stockcount', models.IntegerField(default=0, verbose_name='库存')),
                ('gupdate', models.DateTimeField()),
                ('copa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Copa')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortid', models.IntegerField(default=0)),
                ('sortname', models.CharField(max_length=20)),
                ('sortimg', models.ImageField(default=None, storage=usercenter.storage.ImageStorage(), upload_to='image', verbose_name='图片')),
                ('sortdesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodName', models.CharField(max_length=30)),
                ('goodPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyCount', models.IntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinish', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('orderTime', models.DateTimeField()),
                ('orderNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('addr', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=30)),
                ('uPassword', models.CharField(max_length=20)),
                ('uEmail', models.CharField(max_length=30)),
                ('uPhoneNumber', models.CharField(max_length=15)),
                ('uRegDate', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='userOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Orders'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.GoodSort'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo'),
        ),
        migrations.AddField(
            model_name='addrinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo'),
        ),
    ]
