# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import usercenter.storage


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgname', models.CharField(max_length=30, verbose_name='轮播图名称')),
                ('img', models.ImageField(default=None, storage=usercenter.storage.ImageStorage(), upload_to='image', verbose_name='图片')),
            ],
        ),
    ]
