# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_index_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addrinfos', to='usercenter.UserInfo'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='goodsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='usercenter.Goods'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='usercenter.UserInfo'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='copa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='usercenter.Copa'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodsort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='usercenter.GoodSort'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='usercenter.Goods'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='usercenter.Orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='usercenter.UserInfo'),
        ),
    ]
