# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0005_auto_20180506_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsort',
            options={},
        ),
    ]
