# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0006_auto_20180506_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
    ]
