# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0007_auto_20180506_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goodsid',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uEmail',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uName',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uPassword',
            new_name='upassword',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uPhoneNumber',
            new_name='uphonenumber',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='uRegDate',
            new_name='uregDate',
        ),
    ]
